### ISSUE TITLE
3.3 Add documents to data structure

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#10]
[issue 3](https://github.com/CS180-spring/cs180-22-seg_fault/issues/4)
## Priority 
1
## Story Points
2
## Test Cases
Check document is stored in the data structure
Return error if file does not exist
Return error if duplicate file

**Comment by nchannoob** [comment]
3. As a user, I want to be able to add files to my data storage for safekeeping.

**Comment by nibchao** [comment]
Reviewed by Nicholas Chao and closed by Francisco Bustamante https://github.com/CS180-spring/cs180-22-seg_fault/pull/23
