### ISSUE TITLE
4.1 Remove document from structure

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#11]
[Issue 4](https://github.com/CS180-spring/cs180-22-seg_fault/issues/3)

## Priority 
1
## Story Points
1
## Test Cases
Remove document & verify removal
Remove non-existant document
Remove document twice

**Comment by nchannoob** [comment]
https://github.com/CS180-spring/cs180-22-seg_fault/issues/3

**Comment by nibchao** [comment]
Reviewed and closed by Francisco Bustamante https://github.com/CS180-spring/cs180-22-seg_fault/pull/41
