### ISSUE TITLE
1.1 Search through data structure

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#12]
[Issue 1](https://github.com/CS180-spring/cs180-22-seg_fault/issues/7)
## Priority 
1
## Story Points
3
## Test Cases
Take in user input for document name
Iterate through vector of documents to filter by document name
If matching document name is found, return true; else if entire vector is iterated through and matching case for user input is still not found, return false

**Comment by nchannoob** [comment]
Reviewed and closed by Bahman Baidar https://github.com/CS180-spring/cs180-22-seg_fault/pull/25
