### ISSUE TITLE
6.1 Create a terminal UI

### ISSUE THREAD

**Issue by frab6562** [CS180-spring/cs180-22-seg_fault#17]
[Issue 6](https://github.com/CS180-spring/cs180-22-seg_fault/issues/16)

## Priority 
3
## Story Points
2
## Test Cases
Terminal menu displays CRUD options for documents
Terminal menu shows create and editing of collections

**Comment by nibchao** [comment]
Reviewed by Bahman Baidar and closed by Nicholas Chao https://github.com/CS180-spring/cs180-22-seg_fault/pull/44
