### ISSUE TITLE
2.1 Implement a sort by name function

### ISSUE THREAD

**Issue by frab6562** [CS180-spring/cs180-22-seg_fault#21]
[Issue 2](https://github.com/CS180-spring/cs180-22-seg_fault/issues/5)

## Priority 
2

## Story points
3

## Test cases 
Files can be sorted by alphabetical name ascending
Files can be sorted by alphabetical name descending
Return a vector of Document* that contains the sorted documents

**Comment by nibchao** [comment]
Reviewed and closed by Nicholas Chao https://github.com/CS180-spring/cs180-22-seg_fault/pull/43
