### ISSUE TITLE
6.2 Display the contents of a collection 

### ISSUE THREAD

**Issue by frab6562** [CS180-spring/cs180-22-seg_fault#28]
[Issue 6](https://github.com/CS180-spring/cs180-22-seg_fault/issues/16)

## Priority 
3
## Story Points
2
## Test Cases
Terminal menu displays CRUD options for documents
Terminal menu shows create and editing of collections

**Comment by nibchao** [comment]
Reviewed by Nicholas Chao and closed by Bahman Baidar https://github.com/CS180-spring/cs180-22-seg_fault/pull/29
