### ISSUE TITLE
9.1 As a user, I want an interface to login and access the document system

### ISSUE THREAD

**Issue by teeohdoor** [CS180-spring/cs180-22-seg_fault#33]
[Issue 9](https://github.com/CS180-spring/cs180-22-seg_fault/issues/34)

## Priority 
2
## Story Points
4
## Test Cases
Interface has the necessary functions to display each menu
The interface handles found and unknown user accounts correctly

**Comment by nibchao** [comment]
Reviewed and closed by Nicholas Chao, Francisco Bustamante, Bahman Baidar #56
