### ISSUE TITLE
3.7 Deleting CSV files

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#37]
[Issue 3](https://github.com/CS180-spring/cs180-22-seg_fault/issues/4)

## Priority 
2

## Story points
4

## Test cases 
JSON files can be deleted
Deleting the JSON file deletes the file from the user system
Deleting the JSON file properly removes it from the collection (if it's in one)

**Comment by nibchao** [comment]
Reviewed and closed by Nicholas Chao and Francisco Bustamante #52
