### ISSUE TITLE
3.2 Design the document data class

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#8]
[Issue 3](https://github.com/CS180-spring/cs180-22-seg_fault/issues/4)
## Priority
1
## Story points
2
## Test Cases
Holds document name
Holds document location
Holds document tags

**Comment by nchannoob** [comment]
3. As a user, I want to be able to add files to my data storage for safekeeping

**Comment by nibchao** [comment]
Reviewed and closed by Nicholas Chao https://github.com/CS180-spring/cs180-22-seg_fault/pull/13
