### ISSUE TITLE
3.1 Design the document data structure

### ISSUE THREAD

**Issue by samed425** [CS180-spring/cs180-22-seg_fault#9]
[isssue 3](https://github.com/CS180-spring/cs180-22-seg_fault/issues/4)
## Priority 
1
## Story Points
3
## Test Cases
Holds added documents with all of their data

**Comment by nchannoob** [comment]
Reviewed and closed by Nicholas Chao https://github.com/CS180-spring/cs180-22-seg_fault/pull/13
